# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true
# MD013: Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false
# MD033: Allow inline HTML (needed for badges, special formatting)
MD033: false
# MD041: First line in file should be a top-level heading
MD041: false
# MD024: Multiple headings with the same content
MD024:
  siblings_only: true
# MD046: Code block style
MD046:
  style: fenced
