name: Docs Guard

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'git-hooks/python/docs_validate.py'
      - '.github/workflows/docs-guard.yml'
  push:
    branches: [main]
    paths:
      - 'docs/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyyaml simhash rapidfuzz

      - name: Run documentation validation
        id: validate
        run: |
          python git-hooks/python/docs_validate.py 2>&1 | tee validation.log
          echo "exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload validation log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-log
          path: validation.log
          retention-days: 30

      - name: Upload registry
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-registry
          path: docs/index/registry.json
          retention-days: 90

      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const log = fs.readFileSync('validation.log', 'utf8');

            const body = `## 📚 Documentation Validation Failed

            \`\`\`
            ${log}
            \`\`\`

            ### Next Steps
            1. Review the errors above
            2. Fix front-matter issues in affected files
            3. See \`docs/DOCUMENTATION-SCHEMA.md\` for schema details
            4. For near-duplicates, merge content into canonical doc

            ### Resources
            - [Documentation Schema](../blob/main/docs/DOCUMENTATION-SCHEMA.md)
            - [Agent Documentation Rules](../blob/main/.agent/base/40-documentation.md)
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Fail if validation failed
        if: steps.validate.outputs.exit_code != '0'
        run: exit 1

  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: 'docs/**/*.md'
          config: '.markdownlint.json'
        continue-on-error: true

  link-check:
    name: Check Dead Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: '--verbose --no-progress --cache --max-cache-age 1d "docs/**/*.md"'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
